[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Wandb = "ad70616a-06c9-5745-b1f1-6a5f42545108"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
KSVD = "778123d0-3295-4563-8004-fb5c576fbcd9"

[compat]
PythonCall = "=0.9.24"

